services:
  app:
    build: .
    ports:
      - '8000:8000'
    restart: unless-stopped

  nginx:
    restart: unless-stopped
    image: nginx
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/user_conf.d:ro
    depends_on:
      - app