name: Test, Build, Push and Deploy

on:
  push:
    branches: [main]

jobs:
  Test:
    name: test api functions
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        
      - name: install requirements for testing
        run: pip install -r requirements.txt

      - name: test the functions
        run: pytest

  build_and_push:
    name: push docker image to docker hub
    runs-on: ubuntu-latest
    needs: [Test]
    steps:
      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          ecr: auto
          logout: true
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_ET_FASTAPI}}

      - name: extract metadata for docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: chykee67/fastapiwithnginx
      
      - name: build and push docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: chykee67/fastapiwithnginx:latest
          labels: ${{steps.meta.outputs.labels}}