name: Build, Push, Deploy

on:
  push:
    branches: [main]

jobs:
  build_and_push:
    name: push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v4
      
      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          ecr: auto
          logout: true
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_ET_FASTAPI}}

      - name: extract metadata for docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: chykee67/fastapiwithnginx
      
      - name: build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: chykee67/fastapiwithnginx:latest
          labels: ${{steps.meta.outputs.labels}}