name: fastapi_docker_build

on:
  push

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build_image
        run: docker build -t fastapi .