name: fastapi_docker_build

on:
  push:
    branches: [main]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build_image
        run: docker build -t chykee67/fastapi:latest .

      - name: Test
        run: |
          pip install pytest
          pytest

      - name: push_image_to_dockerhub
        run: |
          docker login -u chykee67 -p ${{ secrets.DOCKER_ET_FASTAPI }}
          docker push chykee67/fastapi:latest

      - name: Deploy
        env:
          deploy_url: ${{secrets.RENDER_DEPLOY_HOOK_URL}}
        run: |
          curl "$deploy_url"